
name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build and Analyze with Maven
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_AFTER }}
        run: |
          mvn -B clean verify sonar:sonar \
            -Dsonar.projectKey=KRishika01_Take_Home_Assignment_2 \
            -Dsonar.organization=krishika01 \
            -Dsonar.host.url=https://sonarcloud.io